// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

namespace StudentAPI.Data.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20201105064948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentClass.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BCIT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "a4dac49b-b167-46c3-a751-54877d70d378",
                            BCIT_ID = "A01222210",
                            City = "Burnaby",
                            Email = "aa@gmail.com",
                            FirstName = "Yashi",
                            LastName = "Girdhar",
                            MobileNumber = "604-111-1234",
                            Option = "AI",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "9eb10b36-abf6-40bf-9c3a-fb8fe087a271",
                            BCIT_ID = "A01882220",
                            City = "Vancouver",
                            Email = "bb@gmail.com",
                            FirstName = "Frey",
                            LastName = "Tolman",
                            MobileNumber = "604-000-1234",
                            Option = "Web",
                            Set = "A"
                        },
                        new
                        {
                            StudentId = "ac524377-3e66-432e-903f-260697348e6f",
                            BCIT_ID = "A01772230",
                            City = "Surrey",
                            Email = "cc@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            MobileNumber = "604-333-1234",
                            Option = "Cloud",
                            Set = "B"
                        },
                        new
                        {
                            StudentId = "f4bfe031-0d78-4fe2-b37a-ef4bf3e59a1f",
                            BCIT_ID = "A01662240",
                            City = "Burnaby",
                            Email = "dd@gmail.com",
                            FirstName = "Yun",
                            LastName = "Wong",
                            MobileNumber = "604-444-1234",
                            Option = "Web",
                            Set = "A"
                        },
                        new
                        {
                            StudentId = "d990d94e-4ed7-45d9-a340-3e15d8754192",
                            BCIT_ID = "A01552250",
                            City = "Vancouver",
                            Email = "ee@gmail.com",
                            FirstName = "Brian",
                            LastName = "White",
                            MobileNumber = "604-555-1234",
                            Option = "AI",
                            Set = "S"
                        },
                        new
                        {
                            StudentId = "bff01aeb-16aa-4eb7-b8c3-e079d654228c",
                            BCIT_ID = "A01442260",
                            City = "Burnaby",
                            Email = "ff@gmail.com",
                            FirstName = "Jane",
                            LastName = "Kim",
                            MobileNumber = "604-666-1234",
                            Option = "Technical Program",
                            Set = "D"
                        },
                        new
                        {
                            StudentId = "be4eabdb-05e7-4764-99e1-9d77e2edd816",
                            BCIT_ID = "A01332270",
                            City = "Surrey",
                            Email = "gg@gmail.com",
                            FirstName = "Kay",
                            LastName = "K",
                            MobileNumber = "604-777-1234",
                            Option = "AI",
                            Set = "S"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
